# Spring properties
spring:
  application:
     name: routing-service

info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
  routes:
    tags:
      path: /tags/**
      serviceId: tag-service

server:
  port: 8765

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG